In [ ]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import tensorflow as tf 
from keras.layers import Input, Lambda, Dense, Flatten
from keras.models import Model
#from keras.applications.resnet50 import ResNet50
from PIL import Image, ImageChops
from keras.applications.vgg16 import VGG16
from keras.applications.vgg16 import preprocess_input
from keras.preprocessing import image
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Sequential
import numpy as np
import glob
import matplotlib.pyplot as plt
import random

from keras.models import load_model


In [ ]:
pred_path="/content/drive/MyDrive/ColabNotebooks/TB_Chest_Radiography_Database/Val"

In [ ]:
model=load_model("/content/drive/MyDrive/ColabNotebooks/Trained_modelTB.h5")

In [ ]:
Normal_list= []
Normal_list=glob.glob("/content/drive/MyDrive/ColabNotebooks/TB_Chest_Radiography_Database/Val/Normal/*.*")
Tuberculosis_list= glob.glob("/content/drive/MyDrive/ColabNotebooks/TB_Chest_Radiography_Database/Val/Tuberculosis/*.*")

In [ ]:
Normal_list

['/content/drive/MyDrive/ColabNotebooks/TB_Chest_Radiography_Database/Val/Normal/Normal-10.png',
 '/content/drive/MyDrive/ColabNotebooks/TB_Chest_Radiography_Database/Val/Normal/Normal-122.png',
 '/content/drive/MyDrive/ColabNotebooks/TB_Chest_Radiography_Database/Val/Normal/Normal-16.png',
 '/content/drive/MyDrive/ColabNotebooks/TB_Chest_Radiography_Database/Val/Normal/Normal-163.png',
 '/content/drive/MyDrive/ColabNotebooks/TB_Chest_Radiography_Database/Val/Normal/Normal-21.png',
 '/content/drive/MyDrive/ColabNotebooks/TB_Chest_Radiography_Database/Val/Normal/Normal-32.png',
 '/content/drive/MyDrive/ColabNotebooks/TB_Chest_Radiography_Database/Val/Normal/Normal-48.png',
 '/content/drive/MyDrive/ColabNotebooks/TB_Chest_Radiography_Database/Val/Normal/Normal-62.png',
 '/content/drive/MyDrive/ColabNotebooks/TB_Chest_Radiography_Database/Val/Normal/Normal-81.png',
 '/content/drive/MyDrive/ColabNotebooks/TB_Chest_Radiography_Database/Val/Normal/Normal-98.png']

In [ ]:
# If 1 is t first place, it indicate that x-ray  is Normal.
# If 1 is in second place, it indicates that X-rays has signs of TB

Normal_list.extend(Tuberculosis_list)
random.shuffle(Normal_list)
Normal_list

['/content/drive/MyDrive/ColabNotebooks/TB_Chest_Radiography_Database/Val/Tuberculosis/Tuberculosis-7.png',
 '/content/drive/MyDrive/ColabNotebooks/TB_Chest_Radiography_Database/Val/Normal/Normal-16.png',
 '/content/drive/MyDrive/ColabNotebooks/TB_Chest_Radiography_Database/Val/Normal/Normal-48.png',
 '/content/drive/MyDrive/ColabNotebooks/TB_Chest_Radiography_Database/Val/Normal/Normal-21.png',
 '/content/drive/MyDrive/ColabNotebooks/TB_Chest_Radiography_Database/Val/Tuberculosis/Tuberculosis-205.png',
 '/content/drive/MyDrive/ColabNotebooks/TB_Chest_Radiography_Database/Val/Normal/Normal-98.png',
 '/content/drive/MyDrive/ColabNotebooks/TB_Chest_Radiography_Database/Val/Tuberculosis/Tuberculosis-18.png',
 '/content/drive/MyDrive/ColabNotebooks/TB_Chest_Radiography_Database/Val/Normal/Normal-122.png',
 '/content/drive/MyDrive/ColabNotebooks/TB_Chest_Radiography_Database/Val/Tuberculosis/Tuberculosis-55.png',
 '/content/drive/MyDrive/ColabNotebooks/TB_Chest_Radiography_Database/Val/Norm

In [ ]:
L=len(Normal_list)
for i in range(0,L):
  img= image.load_img(Normal_list[i],target_size=(500,500))
  x=image.img_to_array(img)
  x= np.expand_dims(x, axis=0)
  img_data= preprocess_input(x)
  Result= model.predict(img_data)
  print(Result)

[[0. 1.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[1. 0.]]
[[0. 1.]]
[[1. 0.]]
[[0. 1.]]
[[1. 0.]]
[[1. 0.]]
[[0. 1.]]
[[1. 0.]]
[[1. 0.]]
[[0. 1.]]
[[0. 1.]]
[[1. 0.]]
[[9.99887586e-01 1.12391426e-04]]
[[0. 1.]]
[[0. 1.]]
